trigger:
- main

pool:
  name: AMZLINUX

steps:
- script: |
    python3.12 --version
  displayName: 'Check Python Version 3.12'

- script: |
    python3.12 -m pip install --upgrade pip
    if [ -f requirements.txt ]; then python3.12 -m pip install -r requirements.txt; fi
  displayName: 'Install dependencies'

- script: |
    python3.12 -m unittest discover -s $(System.DefaultWorkingDirectory)/azdevops -p '*test*'
  displayName: 'Run Tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/python-app.zip'
    replaceExistingArchive: true
  displayName: 'Package Code'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  
    ArtifactName: 'python-app-artifact'  
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'
